### ISSUE TITLE
Способ инициализации

### ISSUE THREAD

**Issue by mercuree** [d9i2r2t1/GTM-template-tag-VK-pixel#1]
Сейчас шаблон использует глобальную инициализацию:
```javascript
    VK.Retargeting.Init('VK-RTRG-...')
    VK.Retargeting.Hit()
```
Такой способ глобально определяет id пикселя. Если другой VK пиксель был инициализирован до этого (например вне GTM кода), его id будет затерт. А события могут дублироваться в последний инициализированный пиксель. 

VK api позволяет делать инициализацию другим способом:
```javascript
   var vk_pixel = VK.Pixel('VK-RTRG-...');
   vk_pixel.Hit();
   vk_pixel.ProductEvent('...')
```

Можно ли реализовать такой способ через Custom Templates API?

**Comment by d9i2r2t1** [comment]
Я знаю об этой проблеме.
Но инициализацию другим способом нужно делать через конструктор (оператор **new**):
```js
var vk_pixel = new VK.Pixel('VK-RTRG-...');
```

А этого Custom Templates API, к сожалению, не позволяет (в нем нельзя использовать конструкторы).

Подробнее почитать можно [тут](https://developers.google.com/tag-manager/templates/sandboxed-javascript).

Как вариант решения проблемы - перед каждым событием инициализировать пиксель который уже стоит на сайте (например, который вне ГТМ).

**Comment by mercuree** [comment]
Может быть имеет смысл сначала сохранять первоначальное значение `VK.Retargeting.pixelCode`, и возвращать его после вызова пикселей через шаблон (с помощью Init)?
```javascript
  // предположим, что изначально установлен VK-RTRG-123
  // VK.Retargeting.Init('VK-RTRG-123');

  // через шаблон подключается другой ID
      VK.Retargeting.Init('VK-RTRG-456');
      VK.Retargeting.Hit();
      VK.Retargeting.ProductEvent(...);
  
  // Отправили все, что нужно. Возвращаем значение
    VK.Retargeting.Init('VK-RTRG-123');
```

**Comment by d9i2r2t1** [comment]
Согласен, спасибо за идею.
Добавлю в UI поле для ввода ID уже установленного пикселя и буду его инициализировать в конце работы шаблона.
